Feature/#199 - 학교 학과 검색어 자동완성 기능 추가
SWM-TEAM-SSH/dart-server pull request #204
Opened 2024-06-29 09:32 UTC by chhs2131

## ✨ 요약
- 학교 학과 검색어 자동완성 기능 추가
- IssueNumber
  - close #199

<br/>

## 😊 주요 변경점
- 특정 키워드로 시작하는 학교명을 통해 `학교 리스트`를 반환합니다.
- 특정 키워드와 일치하는 학교명 + 특정 키워드로 시작하는 학과명을 통해 `학교 리스트`를 반환합니다.

<br/>

## 📙 기타

활용 예시
![Jun-06-2024 20-48-45](https://github.com/SWM-TEAM-SSH/dart-server/assets/10378777/e727724e-8f59-475b-8476-3564534575b0)

<br/>

2024-06-29 10:32 UTC, tigermint requested changes

2024-06-29 10:32 UTC, tigermint commented on build.gradle
다른 PR에 정리해놨었는데,,, 아직 합치질 못했었는데 이미 해놓으셨군요,,,
다음번에 issue 하나 파서 build.gradle 버전, 의존성 정리 필요해보입니다

2024-06-29 10:32 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/domain/University.java
필드 값 변경 시 flyway 스키마 변경도 함께 필요합니다!

2024-06-29 10:32 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/dto/UniversityResponse.java
`@Getter`, `@Setter` 함께 사용하기와 `@Data` 사용하기 중 어떤게 더 나은 것 같으신가요?

2024-06-29 10:32 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/service/UniversityService.java
학교만 search 하는 로직에는 Mapper 를 사용하고 학교/학과 둘다 Search 하는 로직에는 Mapper를 사용하지 않아 통일시키는게 좋아보여요 :D

2024-06-29 10:32 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
1. `findTop20ByNameStartsWith()` 메서드에서 LIMIT 제한은 비즈니스 요구사항이니 파라미터에서 주입해 유연성을 높이는건 어떨까요?
2. UniversityRepository라는 도메인 영역의 Response라 String으로 Response 주기보단, List<University> 로 응답 주고 서비스 로직에서 적절한 UniversityResponse 형태로 변경시켜주는게 좋을 것 같은데 어떠신가요?

2024-06-29 14:58 UTC, chhs2131 commented on build.gradle
좋습니다~

2024-06-29 14:58 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/domain/University.java
우선 DB 데이터는 혹시 몰라서 그대로 두었습니다~ 일단 영속성객체 복잡성만 줄여봤습니다!

2024-06-29 15:09 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/service/UniversityService.java
그러네요! Mapper를 사용하는쪽으로 수정해볼게요~

2024-06-29 15:57 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
FetchJoin Distinct 문제 때문에 1번 적용을 못했었는데 Pageable을 통한 꼼수(?)를 찾아서 적용했습니다. (DB 정규화가 이럴때 발목을 잡네요)

2번도 좋습니다! 다만 University가 이후 리팩터링 진행할 `User`나 `Auth` 부분과도 의존이 많아 해당 부분들을 우선(비교적 복잡성이 낮은 시점에) 리팩터링 한 뒤에, 내부 요소들을 모두 ValueObject로 대체하는 것이 좋을 것 같은데 이 방향은 어떠신가요?

2024-06-29 16:02 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/dto/UniversityResponse.java
개인적으로 @Data를 사용하면 실제 필요한 것보다 더 많은 코드가 생성된다고 생각합니다. 관련한 기능 전체를 사용하지 않을 것이라면 하나씩 지정하는게 좋다고 생각합니다! 

가능하다면 자바 버전을 올려 Record 클래스를 사용하는 것이 가장 깔끔하고 안정적일 것 같습니다. :)

@Data: https://projectlombok.org/features/Data

2024-06-30 05:46 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
저는 2번은 findAllByNameStartsWith() 메서드의 List<String>을 List<University> 로 처리한 후 외부에서 Dto에 관련된 요소 변환처리가 좋을 것 같단 의미였는데, 지금 하고 계신 이야기가 이 말이 맞나요??

1번은 최고!

2024-06-30 16:07 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
comment에서 꺽쇠`<>`쓰면 내용이 안보이네요 ㅋㅋㅋ

Unviersity로 가져오는 것을 말했던 것이군요! 우선 반환자체를 `List<University>`로 수정하거나, 메서드명을 반환타입을 더 잘 나타내게 수정해야 할 것 같습니다. 일단 위에서 말했던 고민은 아래와 같은 내용입니다. 한번 확인해주세요 ㅎㅎ

---

저는 이후에 University 내부에 Name(대학명) 을 VO로 만들고 조회결과가 이것이 되게 하려고 합니다. (jpa count메서드에 반환값은 int인 것처럼....) 이렇게 생각한 이유는 현재 DB 정규화가 되어있지 않아 ID값이 무의미하여 `대학명` 자체만 활용가능하고, 조회한 값에 대해 영속성 관리가 필요하지 않다고 판단해서인데요.

스읍... 고민을 하게 된 이유는 저희가 사용하는 Entity가 영속성 + 도메인 두개의 역할을 모두 가지고 있어서인 것 같네요. 어떻게 생각하시나요?

2024-06-30 16:20 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
제가 정확히 이해한게 맞는진 모르겠지만..
```
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.List;

public interface UniversityRepository extends JpaRepository<University, Long> {

    @Query("SELECT new com.example.UniversityNameVO(u.name) FROM University u WHERE u.name = :name")
    UniversityNameVO findByName(@Param("name") String name);

    @Query("SELECT new com.example.UniversityNameVO(u.name) FROM University u")
    List<UniversityNameVO> findAllNames();
}

```

이런 느낌인지 싶네요?

구현에 일관성이나 단순성(JPQL 작성하지 않아도 됨) 만 보면 Entity로 반환받는게 편해보이긴 하지만, 성능 면에서나(불필요한 데이터 로드 필요 없음) or 어짜피 JPQL을 사용해야한다면 저렇게 NameVO를 통해서 추출하는 것도 좋아보여요!

2024-07-02 12:34 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
문제가 현재 학교와 학과가 정규화되지 않은채로 하나로 되어있어서 반환할 값이 좀 애매해요! 그런 이유로 최초에 학교명을 String으로 반환한 것 같습니다 ㅎㅎ

'학교명'에 해당하는 학교가 여러개이고, 관련한 `university_id`나 `department` 값은 `group by`절에 없어서 의미 없는 값을 강제로 리턴해야된다는 문제가 있습니다..! 

![image](https://github.com/SWM-TEAM-SSH/dart-server/assets/10378777/92ab2c0f-36cc-4f08-9198-e5de69768a55)

2024-07-03 14:54 UTC, tigermint commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
`distinct` 로는 불가능한가요?

2024-07-03 15:10 UTC, chhs2131 commented on src/main/java/com/ssh/dartserver/domain/university/infra/UniversityRepository.java
반환이 Unversity일때 말씀하시는거면 (id, name, department) 조합이라 정규화 안된 상태에서는 distinct 걸어도 결과가 동일하다고 생각했는데 혹시 제가 아는 동작이랑 좀 다를까용?? (group by를 못쓰니깐)

서울대 검색한다고하면 

|id|name|department|
|---|---|---|
|1|서울대학교|사회과|
|2|서울대학교|컴퓨터공학과|

2024-07-05 15:46 UTC, merged